#LOGISTIC REGRESSION FOR THE TITANIC DATA SET PROBLEM.
#SETTING THE PATH FOR THE FILE.
setwd("C:/Users/prakhar/Desktop/titanic")

#LOADING THE DATA AND REPLACE MISSING VALUES WITH NA.
mydata<-read.csv("train.csv",header = T,na.strings = c(""))
head(mydata)
summary(mydata)

#NUMBER OF MISSING VALUES FOR EACH COLUMN.
sapply(mydata,function(x) sum(is.na(x)))

#CHECK FOR HOW MANY DIFFERENT VALUES FOR EACH FIGURE.
sapply(mydata,function(x) length(unique(x)))

#CHECK FOR MISSING VALUES
#R HAS A SPECIAL PACKAGE FOR PLOTTING THE MISSING VALUES WITH THE OBSERVED VALUES.
#THE KEYWORD MISSMAP WILL HELP US TO PLOT THE MISSING VALUES.
install.packages("Amelia")
installed.packages("Amelia")
library(Amelia)
missmap(mydata,main = "missing values vs observed values")

#THE VARIABLE CABIN HAS TOO MANY MISSING VALUES,SO WE WILL NOT USE IT.
#WE WILL ALSO DROP PASSENGERID VARIABLE.

data<-subset(mydata,select = c(2,3,4,5,6,7,8,10,12))
data

#NOW TAKING CARE OF MISSING VALUES.
#WE WILL REPLACE THE MISSING VALUES WITH THE MEAN VALUES.
data$Age[is.na(data$Age)]<-mean(data$Age,na.rm = T)
data

#CHECKING MISSING VALUES FOR CATEGORICAL VARIABLES.
#FACTORS IN R ARE USED FOR DEALING WITH CATEGORICAL VARIABLES.
is.factor(data$Sex)
is.factor(data$Embarked)

#FOR BETTER UNDERSTANDING OF HOW R IS GOING TO DEAL WITH THE CATEGORICAL VARIABLES.
#CONTRATS FUNCTION WILL TELL US HOW VARIABLES ARE DUMMIFIED BY R AND HOW TO INTERPRET THEM IN MODEL.
contrasts(data$Sex)
#IN VARIBALE SEX,FEMALE WILL BE USED AS REFERENCE.

contrasts(data$Embarked)
#HERE THERE ARE 2 MISSING ROWS,SO WE WILL REMOVE THOSE ROWS. WE CAN ALSO REPLACE THEM TAKING MEAN.
data<-data[!is.na(data$Embarked),]
rownames(data)<-NULL

data

#MODEL FITTING.
#WE WILL SPLIT THE DATA INTO 2 PARTS:
#TRAINING AND TEST.
#THE TRAINIG SET WILL BE USED TO FIT OUR MODEL WHICH WE WILL BW TESTING OVER THE TEST DATA SET.

train<-data[1:800,]
test<-data[801:889,]
train
test

excludes<-names(train)%in%c("Name")
train_mini<-train[!excludes]
train_mini

#MODEL FITTING.
model<-glm(Survived~.,family = binomial(link = 'logit'),data = train_mini)
summary(model)

#ANALYSIS OF VARIANCE
anova(model,test = "Chisq")

install.packages("pscl")
library(pscl)
pR2(model)

#MEASURING THE PREDICTIVE ABILITY OF THE MODEL.
#IF PROBABILITY>0.5 THEN 1,ELSE 0.
#WE WOULD SEE HOW OUR MODEL IS DOING WHEN PREDICTING Y ON A NEW DATA SET.
#BY SETTING PARAMETER TYPE='RESPONSE',R WILL OUPUT PROBABILITIES IN THE FORM OF P(Y=1|X)
#IF P(Y=1|X)>0.5 THEN Y=1 ELSE Y=0.
final.results<-predict(model,newdata = subset(test,select = c(2,3,4,5,6,7,8,9)),type = 'response')
final.results<-ifelse(final.results>0.5,1,0)

misClassificError<-mean(final.results!=test$Survived)
print(paste('Accuracy',1-misClassificError))

#ACCURACY RATE IS 0.84 WHICH IS OK.

#CONFUSION MATRIX
install.packages("caret")
library(caret)
install.packages("e1071")
library(e1071)
confusionMatrix(data = final.results,reference = test$Survived)

install.packages("ROCR")
library(ROCR)

#ROC AND AUC
#ROC IS A CURVE GENERATED BY PLOTTING TRUE POSITIVE RATE AGAINST FALSE POSITIVE RATE.
#AUC: AREA UNDER CURVE,WHICH MEASURES THE PERFORMANCE OF THE MODEL. AUC SHOULD BE CLOSE TO 1.
p<-predict(model,newdata = subset(test,select = c(2,3,4,5,6,7,8,9)),type = 'response')
p
pr<-prediction(p,test$Survived)
pr

#True POSITIVE RATE: SENSTIVITY
#FALSE POSITIVE RATE: SPECIFICITY

prf<-performance(pr,measure = "tpr",x.measure = "fpr")
plot(prf)

auc<-performance(pr,measure = "auc")
auc<-auc@y.values[[1]]
auc



